# Generated by Django 5.1.14 on 2025-11-26 12:51

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRegistroCalendario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_selecionada', models.DateField()),
                ('resumo_diario', models.TextField(blank=True, null=True)),
                ('descricao_matutino', models.TextField(blank=True, null=True)),
                ('descricao_vespertino', models.TextField(blank=True, null=True)),
                ('descricao_noturno', models.TextField(blank=True, null=True)),
                ('status_dia', models.CharField(default='Parcial', max_length=20)),
                ('ultima_atualizacao', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical registro calendario',
                'verbose_name_plural': 'historical registro calendarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PerfilPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10)),
                ('logradouro', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=150)),
                ('bairro', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('grau_tea', models.CharField(choices=[('nivel 1', 'Nível 1'), ('nivel 2', 'Nível 2'), ('nivel 3', 'Nível 3')], max_length=20)),
                ('comorbidades', models.TextField(blank=True)),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B-'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('alergias', models.TextField(blank=True)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('medicacoes', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_selecionada', models.DateField()),
                ('resumo_diario', models.TextField(blank=True, null=True)),
                ('descricao_matutino', models.TextField(blank=True, null=True)),
                ('descricao_vespertino', models.TextField(blank=True, null=True)),
                ('descricao_noturno', models.TextField(blank=True, null=True)),
                ('status_dia', models.CharField(default='Parcial', max_length=20)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
                ('senha', models.CharField(max_length=128)),
                ('nome_social', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('desativado', 'Desativado'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('grau_tea', models.CharField(choices=[('nivel 1', 'Nível 1'), ('nivel 2', 'Nível 2'), ('nivel 3', 'Nível 3')], max_length=20)),
                ('comorbidades', models.TextField(blank=True)),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B-'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('alergias', models.TextField(blank=True)),
                ('total_tarefas_criadas', models.IntegerField(default=0, verbose_name='Total de tarefas criadas')),
                ('total_tarefas_concluidas', models.IntegerField(default=0, verbose_name='Total de tarefas concluídas')),
                ('total_tarefas_pendentes', models.IntegerField(default=0, verbose_name='Total de tarefas pendentes')),
                ('total_tarefas_em_atraso', models.IntegerField(default=0, verbose_name='Total de tarefas em atraso')),
                ('dias_maior_produtividade', models.TextField(blank=True, null=True, verbose_name='Dias de maior produtividade')),
                ('total_situacoes_apresentadas', models.IntegerField(default=0, verbose_name='Total de situações apresentadas')),
                ('total_acertos', models.IntegerField(default=0, verbose_name='Total de acertos')),
                ('total_erros', models.IntegerField(default=0, verbose_name='Total de erros')),
                ('acerto_por_categoria', models.TextField(blank=True, null=True, verbose_name='Acerto por categoria')),
                ('evolucao_temporal', models.TextField(blank=True, null=True, verbose_name='Evolução temporal')),
                ('conquistas_obtidas', models.TextField(blank=True, null=True, verbose_name='Conquistas Obtidas')),
                ('pontuacao_acumulada', models.FloatField(default=0.0, verbose_name='Pontuação Acumulada')),
                ('estatisticas_engajamento', models.TextField(blank=True, null=True, verbose_name='Estatísticas de Engajamento (Frequência de Uso)')),
            ],
        ),
    ]
