# Generated by Django 5.1.14 on 2025-11-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autenticacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
                ('senha', models.CharField(max_length=128)),
                ('nome_social', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('desativado', 'Desativado'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('cep', models.CharField(max_length=10)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('grau_tea', models.CharField(choices=[('nivel 1', 'Nível 1'), ('nivel 2', 'Nível 2'), ('nivel 3', 'Nível 3')], max_length=20)),
                ('comorbidades', models.TextField(blank=True)),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B-'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('alergias', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='recuperacao_senha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=64)),
                ('telefone', models.CharField(max_length=15)),
                ('nova_senha', models.CharField(max_length=128)),
                ('confirmar_senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
                ('senha', models.CharField(max_length=128)),
                ('nome_social', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('desativado', 'Desativado'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('grau_tea', models.CharField(choices=[('nivel 1', 'Nível 1'), ('nivel 2', 'Nível 2'), ('nivel 3', 'Nível 3')], max_length=20)),
                ('comorbidades', models.TextField(blank=True)),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B-'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('alergias', models.TextField(blank=True)),
                ('total_tarefas_criadas', models.IntegerField(default=0, verbose_name='Total de tarefas criadas')),
                ('total_tarefas_concluidas', models.IntegerField(default=0, verbose_name='Total de tarefas concluídas')),
                ('total_tarefas_pendentes', models.IntegerField(default=0, verbose_name='Total de tarefas pendentes')),
                ('total_tarefas_em_atraso', models.IntegerField(default=0, verbose_name='Total de tarefas em atraso')),
                ('dias_maior_produtividade', models.TextField(blank=True, null=True, verbose_name='Dias de maior produtividade')),
                ('total_situacoes_apresentadas', models.IntegerField(default=0, verbose_name='Total de situações apresentadas')),
                ('total_acertos', models.IntegerField(default=0, verbose_name='Total de acertos')),
                ('total_erros', models.IntegerField(default=0, verbose_name='Total de erros')),
                ('acerto_por_categoria', models.TextField(blank=True, null=True, verbose_name='Acerto por categoria')),
                ('evolucao_temporal', models.TextField(blank=True, null=True, verbose_name='Evolução temporal')),
                ('conquistas_obtidas', models.TextField(blank=True, null=True, verbose_name='Conquistas Obtidas')),
                ('pontuacao_acumulada', models.FloatField(default=0.0, verbose_name='Pontuação Acumulada')),
                ('estatisticas_engajamento', models.TextField(blank=True, null=True, verbose_name='Estatísticas de Engajamento (Frequência de Uso)')),
            ],
        ),
    ]
