# Generated by Django 5.1.14 on 2025-11-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexo', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='relatorio',
        ),
        migrations.AlterField(
            model_name='historicalregistrocalendario',
            name='status_dia',
            field=models.CharField(default='Não preenchido', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='tipo_sanguineo',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='registrocalendario',
            name='status_dia',
            field=models.CharField(default='Não preenchido', editable=False, max_length=20),
        ),
    ]
