# Generated by Django 5.1.14 on 2025-11-20 20:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexo', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoricalRegistroCalendario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_selecionada', models.DateField()),
                ('resumo_diario', models.TextField(blank=True, null=True)),
                ('descricao_matutino', models.TextField(blank=True, null=True)),
                ('descricao_vespertino', models.TextField(blank=True, null=True)),
                ('descricao_noturno', models.TextField(blank=True, null=True)),
                ('status_dia', models.CharField(default='Não preenchido', max_length=20)),
                ('ultima_atualizacao', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsavel_pelo_registro', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical registro calendario',
                'verbose_name_plural': 'historical registro calendarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RegistroCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_selecionada', models.DateField()),
                ('resumo_diario', models.TextField(blank=True, null=True)),
                ('descricao_matutino', models.TextField(blank=True, null=True)),
                ('descricao_vespertino', models.TextField(blank=True, null=True)),
                ('descricao_noturno', models.TextField(blank=True, null=True)),
                ('status_dia', models.CharField(default='Não preenchido', max_length=20)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_calendario', to=settings.AUTH_USER_MODEL)),
                ('responsavel_pelo_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_feitos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('paciente', 'data_selecionada')},
            },
        ),
    ]
